"""Contract-test main-owned CodeScene coverage, generation and Markdown lint.

Three rules meet here.

Main owns CodeScene publication, so no pull-request workflow may carry the
token, name the service or invoke its command; the push-to-main publisher is
the only uploader, it uploads rather than checks, and its runs queue per ref
so two pushes cannot race to publish.

Coverage is generated by the shared ``generate-coverage`` action on both lanes.
That half was deferred for a while: the action's manifest-based detection
treats a repository-root ``Cargo.toml`` as Rust, and lading commits one as a
fixture for its own workspace-release scenarios (see
``docs/repository-layout.md``), naming ``crates/`` directories that do not
exist on disk. ``language: python`` skips that path and ``python-source`` holds
the metric to the package, so both are asserted here, along with the ratchet
and the split over which lane archives the report.

And Markdown is linted in CI only through the upstream action, pinned to a
commit.

Workflows are enumerated from the workflow directory and classified by their
triggers rather than named, so a lane added later is covered the day it appears
rather than the day somebody remembers to list it. Both the ``*.yml`` and
``*.yaml`` spellings are read, since either would run.

Pins are asserted by shape, a full 40-hex commit SHA, as
``docs/developers-guide.md`` requires, so a Dependabot bump does not fail the
suite. The CodeScene uploader is the one exception and is asserted by value:
that step must sit at or past the commit resolving ``cs-coverage`` from a
committed manifest, because an unpinned CLI is what broke Cobertura parsing
across the estate, and a bump there is meant to be read rather than waved
through.
"""

from __future__ import annotations

import collections.abc as cabc
import json
import re
import typing as typ
from pathlib import Path

import yaml

type YamlValue = (
    str | int | float | bool | list[YamlValue] | dict[str, YamlValue] | None
)
type Workflow = dict[str, YamlValue]

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW_DIRECTORY = REPOSITORY_ROOT / ".github" / "workflows"
CI_WORKFLOW_PATH = WORKFLOW_DIRECTORY / "ci.yml"
MAIN_COVERAGE_WORKFLOW_PATH = WORKFLOW_DIRECTORY / "coverage-main.yml"
APPROVED_ACTION_REVISIONS_PATH = (
    REPOSITORY_ROOT / "tests" / "support" / "approved_action_revisions.json"
)

UPLOAD_CODESCENE_ACTION = (
    "leynos/shared-actions/.github/actions/upload-codescene-coverage"
)
#: The uploader at the commit that resolves cs-coverage from a committed
#: manifest rather than the latest release. Asserted whole rather than by
#: prefix: a pin that drifted to a branch or a tag would still start with the
#: same path.
UPLOAD_CODESCENE_PIN = (
    f"{UPLOAD_CODESCENE_ACTION}@a5765019912a8ab6882b12db049c7cde635f3a85"
)
GENERATE_COVERAGE_ACTION = "leynos/shared-actions/.github/actions/generate-coverage"
#: Any reference to the coverage action. Matching an unpinned form too is
#: deliberate: a step that moved to a branch must still be recognised as a
#: coverage step and then fail the pin assertion, rather than dropping out of
#: the set and passing every test by absence.
GENERATE_COVERAGE_ANY_REF = re.compile(rf"^{re.escape(GENERATE_COVERAGE_ACTION)}@")
COMMIT_PINNED = re.compile(r"@[0-9a-f]{40}$")
SETUP_UV_ACTION = "astral-sh/setup-uv"
UPLOAD_GUARD = (
    "github.event_name == 'push' && github.ref == 'refs/heads/main' && "
    "steps.codescene_token.outputs.available == 'true'"
)
PULL_REQUEST_RATCHET = "${{ github.event_name == 'pull_request' }}"
#: The upstream Markdown linter, pinned to the commit `v24.2.0` points at
#: rather than to the annotated tag object of the same name.
MARKDOWNLINT_ACTION = (
    "DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff"
)
#: Commands that would produce a coverage report outside the shared action.
#: ``--forked`` is named because the invocation this adoption replaced ran
#: pytest under pytest-forked; its return would mean the bespoke lane was back.
HAND_ROLLED_COVERAGE = ("slipcover", "pytest-forked", "--forked")


class CoverageStep(typ.NamedTuple):
    """One shared-action coverage step and the workflow it was found in."""

    path: Path
    job: str
    name: str
    uses: str
    inputs: dict[str, YamlValue]


def _load_workflow(path: Path) -> Workflow:
    """Return one decoded workflow mapping, with its `on:` key restored.

    PyYAML reads a bare `on` as the boolean :data:`True`, so it is moved back
    before any caller looks for a trigger that would otherwise appear absent.
    A contract that missed this would report every workflow as untriggered and
    pass whatever it was asked.

    Returns
    -------
    Workflow
        The decoded workflow document.
    """
    workflow = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(workflow, dict), f"{path} must contain a mapping"
    restored = {
        ("on" if key is True else str(key)): value for key, value in workflow.items()
    }
    return typ.cast("Workflow", restored)


def _workflow_paths() -> list[Path]:
    """Return every workflow file, in both spellings of the extension.

    Returns
    -------
    list of Path
        The workflow documents, sorted by name.
    """
    paths = sorted(
        (*WORKFLOW_DIRECTORY.glob("*.yml"), *WORKFLOW_DIRECTORY.glob("*.yaml")),
        key=lambda path: path.name,
    )
    assert paths, "no workflows found, so this suite proves nothing"
    return paths


def _job(workflow: Workflow, name: str) -> dict[str, YamlValue]:
    """Return a named workflow job."""
    jobs = workflow.get("jobs")
    assert isinstance(jobs, dict), "workflow must declare a jobs mapping"
    job = jobs.get(name)
    assert isinstance(job, dict), f"workflow must declare the {name!r} job"
    return typ.cast("dict[str, YamlValue]", job)


def _jobs(workflow: Workflow) -> dict[str, YamlValue]:
    """Return a workflow's jobs mapping."""
    jobs = workflow.get("jobs")
    assert isinstance(jobs, dict), "workflow must declare a jobs mapping"
    return typ.cast("dict[str, YamlValue]", jobs)


def _step(job: dict[str, YamlValue], name: str) -> dict[str, YamlValue]:
    """Return a named job step."""
    steps = _steps(job)
    step = next(
        (candidate for candidate in steps if candidate.get("name") == name),
        None,
    )
    assert isinstance(step, dict), f"job must declare a {name!r} step"
    return step


def _steps(job: dict[str, YamlValue]) -> list[dict[str, YamlValue]]:
    """Return every mapping in a job's step list."""
    steps = job.get("steps")
    assert isinstance(steps, list), "job must declare a steps list"
    return [
        typ.cast("dict[str, YamlValue]", step)
        for step in steps
        if isinstance(step, dict)
    ]


def _job_steps(
    workflow: Workflow,
) -> cabc.Iterator[tuple[str, dict[str, YamlValue]]]:
    """Yield every ``(job name, step)`` pair in a workflow.

    A job that calls a reusable workflow declares ``uses:`` instead of
    ``steps:``, so it contributes nothing here rather than failing: the
    enumerating contracts below must cross every workflow in the directory,
    and one such job would otherwise stop the sweep at its own file.

    Yields
    ------
    tuple[str, dict[str, YamlValue]]
        The job's name and one of its steps.
    """
    for job_name, job in _jobs(workflow).items():
        if not isinstance(job, dict) or not isinstance(job.get("steps"), list):
            continue
        for step in _steps(typ.cast("dict[str, YamlValue]", job)):
            yield job_name, step


def _uses(step: dict[str, YamlValue]) -> str:
    """Return a step's action reference, rejecting a non-string."""
    uses = step.get("uses")
    assert isinstance(uses, str), f"step uses must be a string, got {uses!r}"
    return uses


def _step_inputs(step: dict[str, YamlValue]) -> dict[str, YamlValue]:
    """Return a step's ``with:`` mapping, defaulting to empty."""
    inputs = step.get("with") or {}
    assert isinstance(inputs, dict), "step inputs must be a mapping"
    return typ.cast("dict[str, YamlValue]", inputs)


def _triggers(workflow: Workflow) -> list[str]:
    """Return the trigger names a workflow declares.

    Returns
    -------
    list of str
        Every trigger name, whichever of the three YAML shapes was used.
    """
    triggers = workflow.get("on")
    match triggers:
        case dict():
            return list(triggers)
        case list():
            return [str(name) for name in triggers]
        case str():
            return [triggers]
        case _:
            return []


def _runs_on_pull_requests(workflow: Workflow) -> bool:
    """Report whether a workflow can run for a pull request."""
    return "pull_request" in _triggers(workflow)


def _is_publisher(workflow: Workflow) -> bool:
    """Report whether a workflow publishes coverage from trunk.

    The predicate is "pushes to main **and** serves no pull request". A
    repository's ``ci.yml`` declares both triggers, and the looser reading
    would make one file required to publish and forbidden from publishing at
    the same time.

    Returns
    -------
    bool
        True when the workflow pushes to main and serves no pull request.
    """
    if _runs_on_pull_requests(workflow):
        return False
    triggers = workflow.get("on")
    push = triggers.get("push") if isinstance(triggers, dict) else None
    branches = push.get("branches") if isinstance(push, dict) else None
    return isinstance(branches, list) and "main" in branches


def _pull_request_workflows() -> list[Path]:
    """Return every workflow that runs on a pull request.

    Enumerated rather than named, so a workflow added later is covered the
    day it appears instead of the day somebody remembers to list it.

    Returns
    -------
    list of Path
        The workflow files whose triggers include `pull_request`.
    """
    found = [
        path
        for path in _workflow_paths()
        if _runs_on_pull_requests(_load_workflow(path))
    ]
    assert found, "no workflow runs on pull requests, so this proves nothing"
    return found


def _coverage_steps() -> list[CoverageStep]:
    """Return every shared-action coverage step across all workflows.

    Returns
    -------
    list of CoverageStep
        One entry per call of the shared coverage action.
    """
    found: list[CoverageStep] = []
    for path in _workflow_paths():
        workflow = _load_workflow(path)
        for job_name, step in _job_steps(workflow):
            uses = step.get("uses")
            if isinstance(uses, str) and GENERATE_COVERAGE_ANY_REF.match(uses):
                found.append(
                    CoverageStep(
                        path=path,
                        job=job_name,
                        name=str(step.get("name") or job_name),
                        uses=uses,
                        inputs=_step_inputs(step),
                    )
                )
    return found


def _codescene_contact_steps(
    workflow: Workflow,
) -> cabc.Iterator[tuple[str, dict[str, YamlValue]]]:
    """Yield every step that could contact CodeScene.

    A step is selected by its behaviour: calling the shared uploader or
    invoking ``cs-coverage``. The caller's label is not evidence, since it can
    change without changing what the step does.

    Yields
    ------
    tuple[str, dict[str, YamlValue]]
        The job name and one CodeScene-contacting step.
    """
    for job_name, step in _job_steps(workflow):
        uses = str(step.get("uses", ""))
        run = str(step.get("run", ""))
        if UPLOAD_CODESCENE_ACTION in uses or "cs-coverage" in run:
            yield job_name, step


def _approved_action_revisions() -> dict[str, object]:
    """Return the offline record of approved composite-action revisions."""
    fixture = json.loads(APPROVED_ACTION_REVISIONS_PATH.read_text(encoding="utf-8"))
    assert isinstance(fixture, dict), "the approved action revisions must map keys"
    return typ.cast("dict[str, object]", fixture)


def test_no_pull_request_workflow_touches_codescene() -> None:
    """Keep CodeScene off every pull-request lane, by any of its three doors.

    The token, the service and the command are checked separately because
    each alone reintroduces the failure this rule exists to prevent: a lane
    holding the credential can upload, a lane naming the project can reach
    it, and a lane running `cs-coverage` fails on whatever CLI the runner
    resolved. Every pull-request workflow is enumerated rather than named.
    """
    for path in _pull_request_workflows():
        text = path.read_text(encoding="utf-8")
        workflow = _load_workflow(path)

        assert "CS_ACCESS_TOKEN" not in text, (
            f"{path.name} must not carry the CodeScene access token"
        )
        assert "codescene.io" not in text, (
            f"{path.name} must not name a CodeScene endpoint"
        )
        assert "cs-coverage" not in text, (
            f"{path.name} must not invoke the CodeScene CLI"
        )

        contacts = list(_codescene_contact_steps(workflow))
        assert not contacts, (
            f"{path.name} must not contact CodeScene: "
            f"{[f'{job}:{step.get("name")}' for job, step in contacts]}"
        )


def test_the_publisher_is_the_only_workflow_using_the_uploader() -> None:
    """No workflow but the publisher may reach for the uploader action.

    The pull-request rule above forbids it on lanes that serve pull requests.
    This one closes the remaining door: a scheduled or dispatch-only workflow
    is neither a pull-request lane nor the publisher, and could otherwise
    upload from any ref without failing a single assertion.
    """
    offenders: list[str] = []
    for path in _workflow_paths():
        if path == MAIN_COVERAGE_WORKFLOW_PATH:
            continue
        workflow = _load_workflow(path)
        offenders.extend(
            f"{path.name}:{job_name}"
            for job_name, step in _job_steps(workflow)
            if UPLOAD_CODESCENE_ACTION in str(step.get("uses", ""))
        )
        # A job calling a reusable workflow has no steps of its own, so its
        # own `uses:` is the only place the uploader could hide there.
        offenders.extend(
            f"{path.name}:{job_name}"
            for job_name, job in _jobs(workflow).items()
            if isinstance(job, dict)
            and UPLOAD_CODESCENE_ACTION in str(job.get("uses", ""))
        )
    assert not offenders, (
        "only coverage-main.yml may use the CodeScene uploader, but it is "
        f"also used by: {', '.join(sorted(offenders))}"
    )


def test_the_pull_request_lane_does_not_fetch_full_history() -> None:
    """Drop the full-history checkout the removed gate needed.

    `fetch-depth: 0` was there so `cs-coverage check` could reach the merge
    base. With the gate gone it is a cost with no purchaser, and leaving it
    would be the visible trace of a lane that still thought it published.
    """
    checkout = _step(
        _job(_load_workflow(CI_WORKFLOW_PATH), "lint-test"), "Check out repository"
    )
    checkout_inputs = _step_inputs(checkout)
    assert checkout_inputs.get("fetch-depth") != 0, (
        "the pull-request lane must not fetch the full Git history"
    )


def test_main_is_the_only_uploader_and_is_pinned() -> None:
    """Publish from pushes to main alone, through a commit-pinned uploader.

    Four claims, each failing on its own. The trigger, because a workflow
    that also ran on pull requests would restore what the first case forbids
    by another route. The mode, because `check` is the call that failed. The
    pin, because an unpinned `cs-coverage` is what broke Cobertura parsing
    across the estate, and this step is now the only place left to fix it.
    And the ref guard, which states at the step what the trigger implies, so
    a trigger added later cannot reach an upload from an unanalysed ref. The
    checksum input is asserted absent by its old name, which the action
    rejects when it carries a value.
    """
    workflow = _load_workflow(MAIN_COVERAGE_WORKFLOW_PATH)
    assert workflow.get("on") == {"push": {"branches": ["main"]}}, (
        "coverage publication must run only on pushes to main"
    )

    upload = _step(
        _job(workflow, "coverage-upload"), "Upload coverage data to CodeScene"
    )
    assert _uses(upload) == UPLOAD_CODESCENE_PIN, (
        "the uploader must be pinned to the manifest-resolving commit"
    )
    upload_inputs = _step_inputs(upload)
    assert upload_inputs.get("mode") == "upload", (
        "the publisher must upload rather than check"
    )
    assert "installer-checksum" not in upload_inputs, (
        "installer-checksum is rejected when non-empty; the manifest pins the CLI"
    )
    assert "archive-checksum" not in upload_inputs, (
        "the action verifies its own manifest archive digest, so callers must "
        "not provide archive-checksum"
    )
    assert "env" not in upload, (
        "the upload is a composite action whose nested steps inherit its env, "
        "so it takes the token as an input instead; see test_codescene_token"
    )
    assert upload.get("if") == UPLOAD_GUARD, (
        "the upload step must be limited to an authenticated push to main"
    )


def test_the_publisher_queues_runs_per_ref() -> None:
    """Queue pushes to main rather than racing or cancelling them.

    Two pushes in quick succession would otherwise contend for the CodeScene
    upload and for the ratchet baseline cache, and a cancelled run would leave
    main's coverage unpublished, so runs queue instead.
    """
    concurrency = _load_workflow(MAIN_COVERAGE_WORKFLOW_PATH).get("concurrency")
    assert isinstance(concurrency, dict), "the publisher must declare concurrency"
    assert "github.ref" in str(concurrency.get("group")), (
        f"concurrency.group must key on the ref, got {concurrency.get('group')!r}"
    )
    assert concurrency.get("cancel-in-progress") is False, (
        "a cancelled publisher leaves main's coverage unpublished, so runs "
        f"must queue, got {concurrency.get('cancel-in-progress')!r}"
    )


def _fixture_mapping(fixture: dict[str, object], section: str) -> dict[str, object]:
    """Return one required mapping from the approved-revisions fixture."""
    value = fixture.get(section)
    assert isinstance(value, dict), f"the fixture must record {section}"
    return typ.cast("dict[str, object]", value)


def _assert_workflow_avoids_retired_references(
    path: Path, retired: dict[str, object]
) -> None:
    """Reject retired action references in one workflow."""
    text = path.read_text(encoding="utf-8")
    for reference, reason in retired.items():
        assert reference not in text, (
            f"{path.name} reaches retired {reference}: {reason}"
        )


def _assert_workflows_avoid_retired_references(retired: dict[str, object]) -> None:
    """Reject retired action references across every workflow."""
    for path in _workflow_paths():
        _assert_workflow_avoids_retired_references(path, retired)


def _coverage_action_revision(
    step: dict[str, YamlValue],
) -> tuple[str, str] | None:
    """Return a coverage composite action and revision from one step."""
    uses = step.get("uses")
    if not isinstance(uses, str) or "@" not in uses:
        return None
    action, revision = uses.rsplit("@", maxsplit=1)
    return (
        (action, revision)
        if action
        in {
            UPLOAD_CODESCENE_ACTION,
            GENERATE_COVERAGE_ACTION,
        }
        else None
    )


def _coverage_action_revisions() -> cabc.Iterator[tuple[str, str]]:
    """Yield every coverage composite action reference in the workflows."""
    for path in _workflow_paths():
        workflow = _load_workflow(path)
        yield from _coverage_action_revisions_in_workflow(workflow)


def _coverage_action_revisions_in_workflow(
    workflow: Workflow,
) -> cabc.Iterator[tuple[str, str]]:
    """Yield coverage composite action references in one workflow."""
    for _job_name, step in _job_steps(workflow):
        reference = _coverage_action_revision(step)
        if reference is not None:
            yield reference


def _assert_coverage_action_has_no_retired_dependency(
    action: str,
    revision: str,
    approved: dict[str, object],
    retired_references: set[str],
) -> None:
    """Require an approved coverage action without retired dependencies."""
    action_revisions = approved.get(action)
    assert isinstance(action_revisions, dict), (
        f"{action} is missing from {APPROVED_ACTION_REVISIONS_PATH.name}"
    )
    detail = action_revisions.get(revision)
    assert isinstance(detail, dict), (
        f"{action}@{revision} is not recorded in {APPROVED_ACTION_REVISIONS_PATH.name}"
    )
    nested_uses = detail.get("nested_uses")
    assert isinstance(nested_uses, dict), (
        f"{action}@{revision} must record its nested actions"
    )
    assert all(isinstance(reference, str) for reference in nested_uses), (
        f"{action}@{revision} must name nested actions as strings"
    )
    nested_references = set(typ.cast("dict[str, object]", nested_uses))
    retired_dependencies = nested_references & retired_references
    assert not retired_dependencies, (
        f"{action}@{revision} reaches retired dependencies: "
        f"{sorted(retired_dependencies)}"
    )


def test_coverage_composites_do_not_reach_retired_action_revisions() -> None:
    """Reject retired pins, including dependencies nested in composites.

    A workflow pin cannot constrain a ``uses:`` entry inside the action it
    calls. The checked-in fixture makes that dependency graph available to
    this offline contract and must be refreshed with each coverage-action pin.
    """
    fixture = _approved_action_revisions()
    retired = _fixture_mapping(fixture, "retired")
    approved = _fixture_mapping(fixture, "approved")
    assert all(isinstance(reference, str) for reference in retired), (
        "retired action references must be strings"
    )
    retired_references = set(typ.cast("dict[str, object]", retired))

    _assert_workflows_avoid_retired_references(retired)
    for action, revision in _coverage_action_revisions():
        _assert_coverage_action_has_no_retired_dependency(
            action, revision, approved, retired_references
        )


def test_both_workflows_install_uv_from_one_commit_pin() -> None:
    """Install uv through the same commit-pinned action on both lanes.

    A third-party action moves under a tag, so both steps name a commit; and
    they name the *same* commit, because the two lanes run the same project
    and a drift between them is a difference nobody chose.
    """
    references = {}
    for path in (CI_WORKFLOW_PATH, MAIN_COVERAGE_WORKFLOW_PATH):
        uses = [
            _uses(step)
            for _job_name, step in _job_steps(_load_workflow(path))
            if str(step.get("uses", "")).startswith(f"{SETUP_UV_ACTION}@")
        ]
        assert len(uses) == 1, f"{path.name} must install uv exactly once, got {uses!r}"
        assert COMMIT_PINNED.search(uses[0]), (
            f"{path.name} must pin {SETUP_UV_ACTION} to a full 40-hex commit "
            f"SHA rather than a mutable tag, got {uses[0]!r}"
        )
        references[path.name] = uses[0]
    assert len(set(references.values())) == 1, (
        f"both lanes must install uv from the same commit, got {references}"
    )


def test_no_workflow_generates_coverage_by_hand() -> None:
    """Coverage comes from the shared action, never from a hand-rolled run."""
    offenders = [
        f"{path.name}:{job_name}:{token}"
        for path in _workflow_paths()
        for job_name, step in _job_steps(_load_workflow(path))
        if isinstance(step.get("run"), str)
        for token in HAND_ROLLED_COVERAGE
        if token in str(step.get("run"))
    ]
    assert not offenders, (
        "these run: steps generate coverage outside the shared action, which "
        "is what the adoption removed: " + ", ".join(sorted(offenders))
    )


def test_both_lanes_generate_coverage_through_the_shared_action() -> None:
    """A pull-request lane and the publisher each generate a report.

    The presence half of the case above: a contract that only forbids the
    hand-rolled invocation is satisfied by deleting coverage altogether.
    """
    steps = _coverage_steps()
    assert steps, "no workflow generates coverage through the shared action"
    lanes = {
        step.path for step in steps if _runs_on_pull_requests(_load_workflow(step.path))
    }
    publishers = {
        step.path for step in steps if _is_publisher(_load_workflow(step.path))
    }
    assert lanes, (
        "no pull-request workflow generates coverage, so nothing measures a "
        "change before it merges"
    )
    assert publishers, (
        "no push-to-main workflow generates coverage, so the ratchet baseline "
        "and the CodeScene upload would have no report"
    )


def test_every_coverage_step_is_pinned_to_a_commit_sha() -> None:
    """Each call names the coverage action at a full 40-hex commit SHA."""
    for step in _coverage_steps():
        assert COMMIT_PINNED.search(step.uses), (
            f"{step.path.name}: the {step.name!r} step must pin the coverage "
            f"action to a full 40-hex commit SHA, got {step.uses!r}"
        )


def test_every_coverage_step_forces_the_python_language_scope() -> None:
    """Detection is overridden, so the fixture Cargo.toml is never resolved."""
    for step in _coverage_steps():
        assert step.inputs.get("language") == "python", (
            f"{step.path.name}: the {step.name!r} step must pass "
            "language: python; without it the action's detection treats the "
            "fixture root Cargo.toml as a buildable crate. Got "
            f"{step.inputs.get('language')!r}"
        )


def test_every_coverage_step_scopes_the_metric_to_the_package() -> None:
    """The measured population stays the package, as it was before adoption."""
    for step in _coverage_steps():
        assert step.inputs.get("python-source") == "./lading", (
            f"{step.path.name}: the {step.name!r} step must pass "
            "python-source: ./lading, or the metric widens to tests and "
            f"fixtures. Got {step.inputs.get('python-source')!r}"
        )


def _assert_coverage_step_has_the_correct_ratchet(step: CoverageStep) -> None:
    """Assert one coverage step has the baseline role its workflow permits."""
    ratchet = step.inputs.get("with-ratchet")
    workflow = _load_workflow(step.path)
    if _is_publisher(workflow):
        assert ratchet == "true", (
            f"{step.path.name}: the publisher must enable its literal ratchet, "
            f"got {ratchet!r}"
        )
    elif _runs_on_pull_requests(workflow):
        assert ratchet in {None, PULL_REQUEST_RATCHET}, (
            f"{step.path.name}: a pull-request lane must condition the ratchet "
            f"on pull_request or omit it, got {ratchet!r}"
        )


def test_only_the_publisher_writes_the_ratchet_baseline() -> None:
    """Keep pushes to main from creating a second baseline writer."""
    for step in _coverage_steps():
        _assert_coverage_step_has_the_correct_ratchet(step)


def test_only_the_publisher_archives_the_action_report() -> None:
    """The pull-request lane declines the archive; the publisher keeps it.

    The pull-request lane uploads its report through a step of its own, and a
    second archive of the same file would be redundant. The publisher's
    archive is the report the CodeScene upload reads, so suppressing it there
    would leave the upload with nothing.
    """
    for step in _coverage_steps():
        publish = step.inputs.get("publish-artefact")
        workflow = _load_workflow(step.path)
        if _runs_on_pull_requests(workflow):
            assert publish in {False, "false"}, (
                f"{step.path.name}: the {step.name!r} step serves pull "
                "requests and must pass publish-artefact: 'false', got "
                f"{publish!r}"
            )
        elif _is_publisher(workflow):
            assert publish is None, (
                f"{step.path.name}: the {step.name!r} step is the publisher "
                "and must leave publish-artefact unset so the action archives "
                f"the report the upload reads, got {publish!r}"
            )


def test_markdown_is_linted_only_through_the_pinned_action() -> None:
    """Lint Markdown in CI through the upstream action and nothing else.

    Two claims, and each fails on its own. The action must be pinned to a
    commit, since the tag object of the same name is immutable but is not a
    commit and names a different kind of thing. And no step may invoke the
    linter itself: a `run:` line reaching for `markdownlint-cli2` resolves
    whatever version the runner happens to have, which is the drift the pin
    exists to stop, and it would sit beside the action rather than replace it
    where nothing was looking.
    """
    lint_test = _job(_load_workflow(CI_WORKFLOW_PATH), "lint-test")

    markdown = _step(lint_test, "Lint Markdown")
    assert _uses(markdown) == MARKDOWNLINT_ACTION, (
        "Markdown must be linted through the action at its commit pin"
    )
    markdown_inputs = _step_inputs(markdown)
    assert markdown_inputs.get("globs") == "**/*.md", (
        "the lint step must cover every Markdown file"
    )

    invocations = [
        step.get("name")
        for step in _steps(lint_test)
        if "markdownlint" in str(step.get("run", ""))
    ]
    assert not invocations, (
        f"CI must not invoke the Markdown linter from a run step: {invocations}"
    )
